version: '3.8'

services:
  producer:
    image: ${{ secrets.DOCKER_USER }}/producer:latest
    restart: always
    depends_on:
      - kafka

  consumer:
    image: ${{ secrets.DOCKER_USER }}/consumer:latest
    restart: always
    depends_on:
      - kafka
      - postgres

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: crimes
      POSTGRES_USER: crimes_owner
      POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
    ports:
      - "5432:5432"

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always

networks:
  default:
    driver: bridge
