version: '3.8'

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.8
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --overprovisioned
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"

  producer:
    build: .
    command: python producer_postgres.py
    depends_on:
      - redpanda
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:9092

  consumer:
    build: .
    command: python consumer_postgres.py
    depends_on:
      - redpanda
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:9092
      - PGHOST=ep-curly-recipe-a50hnh5z-pooler.us-east-2.aws.neon.tech
      - PGDATABASE=crimes
      - PGUSER=crimes_owner
      - PGPASSWORD=npg_QUkH7TfKZlF8
