name: Kafka Postgres Docker Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
    - name: Build Docker image with Kafka
      run: |
        docker build -t my-kafka-image .

    - name: Run Kafka container
      run: |
        docker run -d --name kafka-container -p 2181:2181 -p 9092:9092 my-kafka-image

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build and push the Docker image to Docker Hub
      run: |
        docker build -t $DOCKER_USER/my-kafka-image:${{ github.sha }} .
        docker push $DOCKER_USER/my-kafka-image:${{ github.sha }}

    - name: Show Docker image
      run: |
        docker images

    - name: Check running Docker containers
      run: |
        docker ps
