name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build and push Producer Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/producer:latest -t ${{ secrets.DOCKER_USER }}/producer:${{ github.sha }} -f Dockerfile.producer .
          docker push ${{ secrets.DOCKER_USER }}/producer:latest
          docker push ${{ secrets.DOCKER_USER }}/producer:${{ github.sha }}

      - name: Build and push Consumer Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/consumer:latest -t ${{ secrets.DOCKER_USER }}/consumer:${{ github.sha }} -f Dockerfile.consumer .
          docker push ${{ secrets.DOCKER_USER }}/consumer:latest
          docker push ${{ secrets.DOCKER_USER }}/consumer:${{ github.sha }}

      - name: Logout from Docker Hub
        run: docker logout
