name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify files
      run: |
        ls -la
        echo "Archivos requeridos:"
        echo "- kafkaProducer.py: $( [ -f kafkaProducer.py ] && echo 'OK' || echo 'Falta' )"
        echo "- kafkaConsumer.py: $( [ -f kafkaConsumer.py ] && echo 'OK' || echo 'Falta' )"
        echo "- start.sh: $( [ -f start.sh ] && echo 'OK' || echo 'Falta' )"
        echo "- requirements.txt: $( [ -f requirements.txt ] && echo 'OK' || echo 'Falta' )"

    - name: Verify files
      run: tree

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name == 'push' }}
        tags: ${{ secrets.DOCKER_USER }}/crime-kafka-pg:latest
